extra:
  alternate:
    - name: English
      link: ''
      lang: en
    - name: 中文
      link: zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/RSSerpent/RSSerpent
    - icon: fontawesome/brands/telegram
      link: https://t.me/rsserpent
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3

plugins:
  - git-revision-date
  - i18n:
      default_language: en
      languages:
        en: english
        zh: 中文
      material_alternate: true
  - search:
      prebuild_index: true

remote_branch: doc
repo_name: RSSerpent/RSSerpent
repo_url: https://github.com/RSSerpent/RSSerpent

site_name: RSSerpent Docs
site_url: https://rsserpent.readthedocs.io/

theme:
  favicon: 'assets/logo.png'
  features:
    - header.autohide
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  logo: 'assets/logo.png'
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
