[tool.poetry]
name = "rsserpent"
version = "0.1.0"
description = "🐍 This snake helps you reconnect the Web, with RSS feeds!"
authors = ["Queensferry <queensferry.me@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
arrow = "^1.1.1"
fastapi = "^0.65.2"
importlib-metadata = "^4.5.0"
Jinja2 = "^3.0.1"
pydantic = {extras = ["email"], version = "^1.8.2"}

[tool.poetry.dev-dependencies]
hypothesis = "^6.14.0"
pre-commit = "^2.13.0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
requests = "^2.25.1"
uvicorn = {extras = ["standard"], version = "^0.14.0"}
mkdocs = {version = "^1.2.1", optional = true}
mkdocs-git-revision-date-plugin = {version = "^0.3.1", optional = true}
mkdocs-material = {version = "^7.1.9", optional = true}
mkdocs-static-i18n = {version = "^0.17", optional = true}

[tool.poetry.extras]
doc = ["mkdocs", "mkdocs-git-revision-date-plugin", "mkdocs-material", "mkdocs-static-i18n"]

[tool.black]
include = '\.pyi?$'
target-version = ["py36", "py37", "py38", "py39"]

[tool.coverage.run]
include = ["rsserpent/*"]

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:",
    "pragma: no cover"
]

[tool.isort]
balanced_wrapping = true
classes = ["GUID"]
combine_as_imports = true
lines_after_imports = 2
profile = "black"
src_paths = ["rsserpent", "tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
